app:
  name: "SxuOj"
  mode: "dev"
  port: 8081
  TokenExpireDuration: 720 //小时



log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7


mysql:
  host: "127.0.0.1"
  port: 13306
  user: "root"
  password: "root1234"
  dbname: "sql_demo"
  max_open_conns: 20
  max_idel_conns: 10

redis:
  host: "127.0.0.1"
  port: "162379"
  db: 0
  password: ""
  max_pool_size: 200

