app:
  name: "SxuOj"
  mode: "dev"
  port: 8081
  TokenExpireDuration: 720 //小时
  server: "127.0.0.1"

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

db:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "postgres"
  db_name: "oj"
  ssl_mode: "disable"
  time_zone: "Asia/Shanghai"
  max_open_conns: 20
  max_idel_conns: 10

redis:
  host: "127.0.0.1"
  port: "162379"
  db: 0
  password: ""
  max_pool_size: 200
